version: '3.9'

services:
  api:
    container_name: just-clone-it-api
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/app/src/
      - ./prisma:/app/prisma/
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foo
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
